name: Sleeper Scanner — Nightly Run

on:
  schedule:
    # 11:00 PM UTC = 6:00 PM ET (EST, Nov–Mar)
    # Change to 22:00 for 6PM ET during summer (EDT, Mar–Nov)
    - cron: '0 23 * * 1-5'

  # Run manually anytime from the Actions tab
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    # Give the job permission to write back to the repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Restore database and weights from previous run
      - name: Restore scanner data
        uses: actions/cache@v4
        with:
          path: |
            sleeper.db
            weights.json
          key: sleeper-data-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            sleeper-data-${{ runner.os }}-

      # Run the scanner — this also writes results.json
      - name: Run nightly scan
        run: python scanner.py --all

      # Commit results.json back to the repo so the dashboard can read it
     - name: Commit results to repo
        run: |
          git config user.name  "Sleeper Scanner"
          git config user.email "scanner@noreply.github.com"
          git add -f results.json
          git status
          git diff --staged --quiet || git commit -m "scan: $(date +'%Y-%m-%d') nightly results"
          git push origin main

      # Save updated database and weights for next run
      - name: Save scanner data
        uses: actions/cache/save@v4
        with:
          path: |
            sleeper.db
            weights.json
          key: sleeper-data-${{ runner.os }}-${{ github.run_id }}
